### ISSUE TITLE
Create pipelines

### ISSUE THREAD

**Issue by chrsin** [FAForever/faf-qai#6]
We need the following pipelines:

Create release (Should create a new release of the client)
Continuous Integration. (Should be run on every push and verify the state of the code)

**Comment by Soyvolon** [comment]
CI is done and working, and I have a possible example for CD [here](https://github.com/Soyvolon/CloudNineBot/blob/main/.github/workflows/discord_release.yml) if that is the route we are going.

The linked example uses a string of commands to build the new docker image and remove old versions of it:
`DOCKER_STOP_CMD`
`docker stop bot-run && docker rm bot-run`

`DOCKER_START_CMD`
`docker image prune -f && cd /path/to/source && docker build -t bot-image -f Dockerfile . && docker run -d --name bot-run --restart always -v /path/to/configs:/App/Config -v /path/to/database:/App/Database -p 8080:80 bot-image`

Granted, there will not be a Config volume as the configs are stored as environment secrets, but this, along with [this file](https://github.com/Soyvolon/CloudNineBot/blob/main/.github/workflows/discord_release.yml) is how I usually do CD.

**Comment by Brutus5000** [comment]
The current pipeline is sufficient for my common faf deployment workflow.
